<?php
/**
 * ObjectEzsigntemplatesignerApi
 * PHP version 7.4
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.2.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace eZmaxAPI\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use eZmaxAPI\ApiException;
use eZmaxAPI\Configuration;
use eZmaxAPI\HeaderSelector;
use eZmaxAPI\ObjectSerializer;
use eZmaxAPI\RequestSignature;

/**
 * ObjectEzsigntemplatesignerApi Class Doc Comment
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ObjectEzsigntemplatesignerApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'ezsigntemplatesignerCreateObjectV1' => [
            'application/json',
        ],
        'ezsigntemplatesignerDeleteObjectV1' => [
            'application/json',
        ],
        'ezsigntemplatesignerEditObjectV1' => [
            'application/json',
        ],
        'ezsigntemplatesignerGetObjectV2' => [
            'application/json',
        ],
    ];

    /** @var array[] $objEzmaxConfig **/
    public const objEzmaxConfig = [
        'ezsigntemplatesignerCreateObjectV1' => [
            'permissions' => [
                'All',
            ],
            'usertypeextra' => [
            ],
            'authorizationsources' => [
                'Authorization',
            ],
            'deprecated' => false,
        ],
        'ezsigntemplatesignerDeleteObjectV1' => [
            'permissions' => [
                'All',
            ],
            'usertypeextra' => [
            ],
            'authorizationsources' => [
                'Authorization',
            ],
            'deprecated' => false,
        ],
        'ezsigntemplatesignerEditObjectV1' => [
            'permissions' => [
                'All',
            ],
            'usertypeextra' => [
            ],
            'authorizationsources' => [
                'Authorization',
            ],
            'deprecated' => false,
        ],
        'ezsigntemplatesignerGetObjectV2' => [
            'permissions' => [
                'All',
            ],
            'usertypeextra' => [
            ],
            'authorizationsources' => [
                'Authorization',
            ],
            'deprecated' => false,
        ],
    ];
/**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation ezsigntemplatesignerCreateObjectV1
     *
     * Create a new Ezsigntemplatesigner
     *
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Request $ezsigntemplatesignerCreateObjectV1Request ezsigntemplatesignerCreateObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerCreateObjectV1'] to see the possible values for this operation
     *
     * @throws \eZmaxAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Response
     */
    public function ezsigntemplatesignerCreateObjectV1($ezsigntemplatesignerCreateObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerCreateObjectV1'][0])
    {
        list($response) = $this->ezsigntemplatesignerCreateObjectV1WithHttpInfo($ezsigntemplatesignerCreateObjectV1Request, $contentType);
        return $response;
    }

    /**
     * Operation ezsigntemplatesignerCreateObjectV1WithHttpInfo
     *
     * Create a new Ezsigntemplatesigner
     *
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Request $ezsigntemplatesignerCreateObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerCreateObjectV1'] to see the possible values for this operation
     *
     * @throws \eZmaxAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Response, HTTP status code, HTTP response headers (array of strings)
     */
    public function ezsigntemplatesignerCreateObjectV1WithHttpInfo($ezsigntemplatesignerCreateObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerCreateObjectV1'][0])
    {
        $request = $this->ezsigntemplatesignerCreateObjectV1Request($ezsigntemplatesignerCreateObjectV1Request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ezsigntemplatesignerCreateObjectV1Async
     *
     * Create a new Ezsigntemplatesigner
     *
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Request $ezsigntemplatesignerCreateObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerCreateObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ezsigntemplatesignerCreateObjectV1Async($ezsigntemplatesignerCreateObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerCreateObjectV1'][0])
    {
        return $this->ezsigntemplatesignerCreateObjectV1AsyncWithHttpInfo($ezsigntemplatesignerCreateObjectV1Request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ezsigntemplatesignerCreateObjectV1AsyncWithHttpInfo
     *
     * Create a new Ezsigntemplatesigner
     *
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Request $ezsigntemplatesignerCreateObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerCreateObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ezsigntemplatesignerCreateObjectV1AsyncWithHttpInfo($ezsigntemplatesignerCreateObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerCreateObjectV1'][0])
    {
        $returnType = '\eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Response';
        $request = $this->ezsigntemplatesignerCreateObjectV1Request($ezsigntemplatesignerCreateObjectV1Request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ezsigntemplatesignerCreateObjectV1'
     *
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerCreateObjectV1Request $ezsigntemplatesignerCreateObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerCreateObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ezsigntemplatesignerCreateObjectV1Request($ezsigntemplatesignerCreateObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerCreateObjectV1'][0])
    {

        // verify the required parameter 'ezsigntemplatesignerCreateObjectV1Request' is set
        if ($ezsigntemplatesignerCreateObjectV1Request === null || (is_array($ezsigntemplatesignerCreateObjectV1Request) && count($ezsigntemplatesignerCreateObjectV1Request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ezsigntemplatesignerCreateObjectV1Request when calling ezsigntemplatesignerCreateObjectV1'
            );
        }


        $resourcePath = '/1/object/ezsigntemplatesigner';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ezsigntemplatesignerCreateObjectV1Request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($ezsigntemplatesignerCreateObjectV1Request));
            } else {
                $httpBody = $ezsigntemplatesignerCreateObjectV1Request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        if ($apiKey !== null) {
            $secret = $this->config->getSecret();
            if ($secret !== '') {
                //Let's sign the request
                $headers = array_merge($headers, RequestSignature::getHeadersV1($apiKey, $secret, 'POST', $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''), $httpBody));
            }		
        }

        return new Request(
            'POST',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ezsigntemplatesignerDeleteObjectV1
     *
     * Delete an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerDeleteObjectV1'] to see the possible values for this operation
     *
     * @throws \eZmaxAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \eZmaxAPI\Model\EzsigntemplatesignerDeleteObjectV1Response|\eZmaxAPI\Model\CommonResponseError
     */
    public function ezsigntemplatesignerDeleteObjectV1($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerDeleteObjectV1'][0])
    {
        list($response) = $this->ezsigntemplatesignerDeleteObjectV1WithHttpInfo($pkiEzsigntemplatesignerID, $contentType);
        return $response;
    }

    /**
     * Operation ezsigntemplatesignerDeleteObjectV1WithHttpInfo
     *
     * Delete an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerDeleteObjectV1'] to see the possible values for this operation
     *
     * @throws \eZmaxAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \eZmaxAPI\Model\EzsigntemplatesignerDeleteObjectV1Response|\eZmaxAPI\Model\CommonResponseError, HTTP status code, HTTP response headers (array of strings)
     */
    public function ezsigntemplatesignerDeleteObjectV1WithHttpInfo($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerDeleteObjectV1'][0])
    {
        $request = $this->ezsigntemplatesignerDeleteObjectV1Request($pkiEzsigntemplatesignerID, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\eZmaxAPI\Model\EzsigntemplatesignerDeleteObjectV1Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\eZmaxAPI\Model\EzsigntemplatesignerDeleteObjectV1Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\eZmaxAPI\Model\EzsigntemplatesignerDeleteObjectV1Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\eZmaxAPI\Model\CommonResponseError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\eZmaxAPI\Model\CommonResponseError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\eZmaxAPI\Model\CommonResponseError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\eZmaxAPI\Model\EzsigntemplatesignerDeleteObjectV1Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\eZmaxAPI\Model\EzsigntemplatesignerDeleteObjectV1Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\eZmaxAPI\Model\CommonResponseError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ezsigntemplatesignerDeleteObjectV1Async
     *
     * Delete an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerDeleteObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ezsigntemplatesignerDeleteObjectV1Async($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerDeleteObjectV1'][0])
    {
        return $this->ezsigntemplatesignerDeleteObjectV1AsyncWithHttpInfo($pkiEzsigntemplatesignerID, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ezsigntemplatesignerDeleteObjectV1AsyncWithHttpInfo
     *
     * Delete an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerDeleteObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ezsigntemplatesignerDeleteObjectV1AsyncWithHttpInfo($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerDeleteObjectV1'][0])
    {
        $returnType = '\eZmaxAPI\Model\EzsigntemplatesignerDeleteObjectV1Response';
        $request = $this->ezsigntemplatesignerDeleteObjectV1Request($pkiEzsigntemplatesignerID, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ezsigntemplatesignerDeleteObjectV1'
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerDeleteObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ezsigntemplatesignerDeleteObjectV1Request($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerDeleteObjectV1'][0])
    {

        // verify the required parameter 'pkiEzsigntemplatesignerID' is set
        if ($pkiEzsigntemplatesignerID === null || (is_array($pkiEzsigntemplatesignerID) && count($pkiEzsigntemplatesignerID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $pkiEzsigntemplatesignerID when calling ezsigntemplatesignerDeleteObjectV1'
            );
        }
        if ($pkiEzsigntemplatesignerID < 0) {
            throw new \InvalidArgumentException('invalid value for "$pkiEzsigntemplatesignerID" when calling ObjectEzsigntemplatesignerApi.ezsigntemplatesignerDeleteObjectV1, must be bigger than or equal to 0.');
        }
        

        $resourcePath = '/1/object/ezsigntemplatesigner/{pkiEzsigntemplatesignerID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($pkiEzsigntemplatesignerID !== null) {
            $resourcePath = str_replace(
                '{' . 'pkiEzsigntemplatesignerID' . '}',
                ObjectSerializer::toPathValue($pkiEzsigntemplatesignerID),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        if ($apiKey !== null) {
            $secret = $this->config->getSecret();
            if ($secret !== '') {
                //Let's sign the request
                $headers = array_merge($headers, RequestSignature::getHeadersV1($apiKey, $secret, 'DELETE', $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''), $httpBody));
            }		
        }

        return new Request(
            'DELETE',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ezsigntemplatesignerEditObjectV1
     *
     * Edit an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID pkiEzsigntemplatesignerID (required)
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Request $ezsigntemplatesignerEditObjectV1Request ezsigntemplatesignerEditObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerEditObjectV1'] to see the possible values for this operation
     *
     * @throws \eZmaxAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Response|\eZmaxAPI\Model\CommonResponseError|\eZmaxAPI\Model\CommonResponseError
     */
    public function ezsigntemplatesignerEditObjectV1($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerEditObjectV1'][0])
    {
        list($response) = $this->ezsigntemplatesignerEditObjectV1WithHttpInfo($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, $contentType);
        return $response;
    }

    /**
     * Operation ezsigntemplatesignerEditObjectV1WithHttpInfo
     *
     * Edit an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Request $ezsigntemplatesignerEditObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerEditObjectV1'] to see the possible values for this operation
     *
     * @throws \eZmaxAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Response|\eZmaxAPI\Model\CommonResponseError|\eZmaxAPI\Model\CommonResponseError, HTTP status code, HTTP response headers (array of strings)
     */
    public function ezsigntemplatesignerEditObjectV1WithHttpInfo($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerEditObjectV1'][0])
    {
        $request = $this->ezsigntemplatesignerEditObjectV1Request($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\eZmaxAPI\Model\CommonResponseError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\eZmaxAPI\Model\CommonResponseError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\eZmaxAPI\Model\CommonResponseError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 422:
                    if ('\eZmaxAPI\Model\CommonResponseError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\eZmaxAPI\Model\CommonResponseError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\eZmaxAPI\Model\CommonResponseError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\eZmaxAPI\Model\CommonResponseError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\eZmaxAPI\Model\CommonResponseError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ezsigntemplatesignerEditObjectV1Async
     *
     * Edit an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Request $ezsigntemplatesignerEditObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerEditObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ezsigntemplatesignerEditObjectV1Async($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerEditObjectV1'][0])
    {
        return $this->ezsigntemplatesignerEditObjectV1AsyncWithHttpInfo($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ezsigntemplatesignerEditObjectV1AsyncWithHttpInfo
     *
     * Edit an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Request $ezsigntemplatesignerEditObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerEditObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ezsigntemplatesignerEditObjectV1AsyncWithHttpInfo($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerEditObjectV1'][0])
    {
        $returnType = '\eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Response';
        $request = $this->ezsigntemplatesignerEditObjectV1Request($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ezsigntemplatesignerEditObjectV1'
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  \eZmaxAPI\Model\EzsigntemplatesignerEditObjectV1Request $ezsigntemplatesignerEditObjectV1Request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerEditObjectV1'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ezsigntemplatesignerEditObjectV1Request($pkiEzsigntemplatesignerID, $ezsigntemplatesignerEditObjectV1Request, string $contentType = self::contentTypes['ezsigntemplatesignerEditObjectV1'][0])
    {

        // verify the required parameter 'pkiEzsigntemplatesignerID' is set
        if ($pkiEzsigntemplatesignerID === null || (is_array($pkiEzsigntemplatesignerID) && count($pkiEzsigntemplatesignerID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $pkiEzsigntemplatesignerID when calling ezsigntemplatesignerEditObjectV1'
            );
        }
        if ($pkiEzsigntemplatesignerID < 0) {
            throw new \InvalidArgumentException('invalid value for "$pkiEzsigntemplatesignerID" when calling ObjectEzsigntemplatesignerApi.ezsigntemplatesignerEditObjectV1, must be bigger than or equal to 0.');
        }
        
        // verify the required parameter 'ezsigntemplatesignerEditObjectV1Request' is set
        if ($ezsigntemplatesignerEditObjectV1Request === null || (is_array($ezsigntemplatesignerEditObjectV1Request) && count($ezsigntemplatesignerEditObjectV1Request) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $ezsigntemplatesignerEditObjectV1Request when calling ezsigntemplatesignerEditObjectV1'
            );
        }


        $resourcePath = '/1/object/ezsigntemplatesigner/{pkiEzsigntemplatesignerID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($pkiEzsigntemplatesignerID !== null) {
            $resourcePath = str_replace(
                '{' . 'pkiEzsigntemplatesignerID' . '}',
                ObjectSerializer::toPathValue($pkiEzsigntemplatesignerID),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (isset($ezsigntemplatesignerEditObjectV1Request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \GuzzleHttp\Utils::jsonEncode(ObjectSerializer::sanitizeForSerialization($ezsigntemplatesignerEditObjectV1Request));
            } else {
                $httpBody = $ezsigntemplatesignerEditObjectV1Request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        if ($apiKey !== null) {
            $secret = $this->config->getSecret();
            if ($secret !== '') {
                //Let's sign the request
                $headers = array_merge($headers, RequestSignature::getHeadersV1($apiKey, $secret, 'PUT', $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''), $httpBody));
            }		
        }

        return new Request(
            'PUT',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation ezsigntemplatesignerGetObjectV2
     *
     * Retrieve an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerGetObjectV2'] to see the possible values for this operation
     *
     * @throws \eZmaxAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \eZmaxAPI\Model\EzsigntemplatesignerGetObjectV2Response|\eZmaxAPI\Model\CommonResponseError
     */
    public function ezsigntemplatesignerGetObjectV2($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerGetObjectV2'][0])
    {
        list($response) = $this->ezsigntemplatesignerGetObjectV2WithHttpInfo($pkiEzsigntemplatesignerID, $contentType);
        return $response;
    }

    /**
     * Operation ezsigntemplatesignerGetObjectV2WithHttpInfo
     *
     * Retrieve an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerGetObjectV2'] to see the possible values for this operation
     *
     * @throws \eZmaxAPI\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \eZmaxAPI\Model\EzsigntemplatesignerGetObjectV2Response|\eZmaxAPI\Model\CommonResponseError, HTTP status code, HTTP response headers (array of strings)
     */
    public function ezsigntemplatesignerGetObjectV2WithHttpInfo($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerGetObjectV2'][0])
    {
        $request = $this->ezsigntemplatesignerGetObjectV2Request($pkiEzsigntemplatesignerID, $contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\eZmaxAPI\Model\EzsigntemplatesignerGetObjectV2Response' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\eZmaxAPI\Model\EzsigntemplatesignerGetObjectV2Response' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\eZmaxAPI\Model\EzsigntemplatesignerGetObjectV2Response', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 404:
                    if ('\eZmaxAPI\Model\CommonResponseError' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\eZmaxAPI\Model\CommonResponseError' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\eZmaxAPI\Model\CommonResponseError', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\eZmaxAPI\Model\EzsigntemplatesignerGetObjectV2Response';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\eZmaxAPI\Model\EzsigntemplatesignerGetObjectV2Response',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\eZmaxAPI\Model\CommonResponseError',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation ezsigntemplatesignerGetObjectV2Async
     *
     * Retrieve an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerGetObjectV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ezsigntemplatesignerGetObjectV2Async($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerGetObjectV2'][0])
    {
        return $this->ezsigntemplatesignerGetObjectV2AsyncWithHttpInfo($pkiEzsigntemplatesignerID, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation ezsigntemplatesignerGetObjectV2AsyncWithHttpInfo
     *
     * Retrieve an existing Ezsigntemplatesigner
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerGetObjectV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function ezsigntemplatesignerGetObjectV2AsyncWithHttpInfo($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerGetObjectV2'][0])
    {
        $returnType = '\eZmaxAPI\Model\EzsigntemplatesignerGetObjectV2Response';
        $request = $this->ezsigntemplatesignerGetObjectV2Request($pkiEzsigntemplatesignerID, $contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'ezsigntemplatesignerGetObjectV2'
     *
     * @param  int $pkiEzsigntemplatesignerID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['ezsigntemplatesignerGetObjectV2'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function ezsigntemplatesignerGetObjectV2Request($pkiEzsigntemplatesignerID, string $contentType = self::contentTypes['ezsigntemplatesignerGetObjectV2'][0])
    {

        // verify the required parameter 'pkiEzsigntemplatesignerID' is set
        if ($pkiEzsigntemplatesignerID === null || (is_array($pkiEzsigntemplatesignerID) && count($pkiEzsigntemplatesignerID) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $pkiEzsigntemplatesignerID when calling ezsigntemplatesignerGetObjectV2'
            );
        }
        if ($pkiEzsigntemplatesignerID < 0) {
            throw new \InvalidArgumentException('invalid value for "$pkiEzsigntemplatesignerID" when calling ObjectEzsigntemplatesignerApi.ezsigntemplatesignerGetObjectV2, must be bigger than or equal to 0.');
        }
        

        $resourcePath = '/2/object/ezsigntemplatesigner/{pkiEzsigntemplatesignerID}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($pkiEzsigntemplatesignerID !== null) {
            $resourcePath = str_replace(
                '{' . 'pkiEzsigntemplatesignerID' . '}',
                ObjectSerializer::toPathValue($pkiEzsigntemplatesignerID),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);

        if ($apiKey !== null) {
            $secret = $this->config->getSecret();
            if ($secret !== '') {
                //Let's sign the request
                $headers = array_merge($headers, RequestSignature::getHeadersV1($apiKey, $secret, 'GET', $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''), $httpBody));
            }		
        }

        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
