<?php
/**
 * CommunicationrecipientResponseCompoundTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.17
 * Contact: support-api@ezmax.ca
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.2.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eZmaxAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CommunicationrecipientResponseCompoundTest Class Doc Comment
 *
 * @category    Class
 * @description A Communicationreciient Object
 * @package     eZmaxAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CommunicationrecipientResponseCompoundTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CommunicationrecipientResponseCompound"
     */
    public function testCommunicationrecipientResponseCompound()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pkiCommunicationrecipientID"
     */
    public function testPropertyPkiCommunicationrecipientID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eCommunicationrecipientObjecttype"
     */
    public function testPropertyECommunicationrecipientObjecttype()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiAgentID"
     */
    public function testPropertyFkiAgentID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiBrokerID"
     */
    public function testPropertyFkiBrokerID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiContactID"
     */
    public function testPropertyFkiContactID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiCustomerID"
     */
    public function testPropertyFkiCustomerID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEmployeeID"
     */
    public function testPropertyFkiEmployeeID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzsignsignerID"
     */
    public function testPropertyFkiEzsignsignerID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiFranchiseofficeID"
     */
    public function testPropertyFkiFranchiseofficeID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiUserID"
     */
    public function testPropertyFkiUserID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiAgentincorporationID"
     */
    public function testPropertyFkiAgentincorporationID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiAssistantID"
     */
    public function testPropertyFkiAssistantID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiExternalbrokerID"
     */
    public function testPropertyFkiExternalbrokerID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzcomagentID"
     */
    public function testPropertyFkiEzcomagentID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiNotaryID"
     */
    public function testPropertyFkiNotaryID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiRewardmemberID"
     */
    public function testPropertyFkiRewardmemberID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiSupplierID"
     */
    public function testPropertyFkiSupplierID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eCommunicationrecipientType"
     */
    public function testPropertyECommunicationrecipientType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objDescriptionstatic"
     */
    public function testPropertyObjDescriptionstatic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objEmailstatic"
     */
    public function testPropertyObjEmailstatic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objPhonestatic"
     */
    public function testPropertyObjPhonestatic()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
