<?php
/**
 * CustomNotificationtestgetnotificationtestsResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: support-api@ezmax.ca
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 7.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eZmaxAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CustomNotificationtestgetnotificationtestsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description A Notificationtest Object in the context of getNotificationtests
 * @package     eZmaxAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CustomNotificationtestgetnotificationtestsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CustomNotificationtestgetnotificationtestsResponse"
     */
    public function testCustomNotificationtestgetnotificationtestsResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pkiNotificationtestID"
     */
    public function testPropertyPkiNotificationtestID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objNotificationtestName"
     */
    public function testPropertyObjNotificationtestName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiNotificationsubsectionID"
     */
    public function testPropertyFkiNotificationsubsectionID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sNotificationtestFunction"
     */
    public function testPropertySNotificationtestFunction()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sNotificationtestNameX"
     */
    public function testPropertySNotificationtestNameX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eNotificationpreferenceStatus"
     */
    public function testPropertyENotificationpreferenceStatus()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iNotificationtest"
     */
    public function testPropertyINotificationtest()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
