<?php
/**
 * EzdoctemplatedocumentRequestCompoundTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eZmaxAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EzdoctemplatedocumentRequestCompoundTest Class Doc Comment
 *
 * @category    Class
 * @description A Ezdoctemplatedocument Object and children
 * @package     eZmaxAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EzdoctemplatedocumentRequestCompoundTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EzdoctemplatedocumentRequestCompound"
     */
    public function testEzdoctemplatedocumentRequestCompound()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pkiEzdoctemplatedocumentID"
     */
    public function testPropertyPkiEzdoctemplatedocumentID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiLanguageID"
     */
    public function testPropertyFkiLanguageID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzsignfoldertypeID"
     */
    public function testPropertyFkiEzsignfoldertypeID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzdoctemplatetypeID"
     */
    public function testPropertyFkiEzdoctemplatetypeID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzdoctemplatefieldtypecategoryID"
     */
    public function testPropertyFkiEzdoctemplatefieldtypecategoryID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzdoctemplatedocumentPrivacylevel"
     */
    public function testPropertyEEzdoctemplatedocumentPrivacylevel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bEzdoctemplatedocumentIsactive"
     */
    public function testPropertyBEzdoctemplatedocumentIsactive()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objEzdoctemplatedocumentName"
     */
    public function testPropertyObjEzdoctemplatedocumentName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
