<?php
/**
 * EzsignformfieldgroupResponseCompoundTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.11.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eZmaxAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EzsignformfieldgroupResponseCompoundTest Class Doc Comment
 *
 * @category    Class
 * @description An Ezsignformfieldgroup Object and children to create a complete structure
 * @package     eZmaxAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EzsignformfieldgroupResponseCompoundTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EzsignformfieldgroupResponseCompound"
     */
    public function testEzsignformfieldgroupResponseCompound()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pkiEzsignformfieldgroupID"
     */
    public function testPropertyPkiEzsignformfieldgroupID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzsigndocumentID"
     */
    public function testPropertyFkiEzsigndocumentID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignformfieldgroupType"
     */
    public function testPropertyEEzsignformfieldgroupType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignformfieldgroupSignerrequirement"
     */
    public function testPropertyEEzsignformfieldgroupSignerrequirement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignformfieldgroupLabel"
     */
    public function testPropertySEzsignformfieldgroupLabel()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignformfieldgroupStep"
     */
    public function testPropertyIEzsignformfieldgroupStep()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignformfieldgroupDefaultvalue"
     */
    public function testPropertySEzsignformfieldgroupDefaultvalue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignformfieldgroupFilledmin"
     */
    public function testPropertyIEzsignformfieldgroupFilledmin()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignformfieldgroupFilledmax"
     */
    public function testPropertyIEzsignformfieldgroupFilledmax()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bEzsignformfieldgroupReadonly"
     */
    public function testPropertyBEzsignformfieldgroupReadonly()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignformfieldgroupMaxlength"
     */
    public function testPropertyIEzsignformfieldgroupMaxlength()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bEzsignformfieldgroupEncrypted"
     */
    public function testPropertyBEzsignformfieldgroupEncrypted()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignformfieldgroupTextvalidation"
     */
    public function testPropertyEEzsignformfieldgroupTextvalidation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignformfieldgroupRegexp"
     */
    public function testPropertySEzsignformfieldgroupRegexp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignformfieldgroupTextvalidationcustommessage"
     */
    public function testPropertySEzsignformfieldgroupTextvalidationcustommessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tEzsignformfieldgroupTooltip"
     */
    public function testPropertyTEzsignformfieldgroupTooltip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignformfieldgroupTooltipposition"
     */
    public function testPropertyEEzsignformfieldgroupTooltipposition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aObjEzsignformfield"
     */
    public function testPropertyAObjEzsignformfield()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aObjDropdownElement"
     */
    public function testPropertyAObjDropdownElement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "aObjEzsignformfieldgroupsigner"
     */
    public function testPropertyAObjEzsignformfieldgroupsigner()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
