<?php
/**
 * EzsignsignatureRequestTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eZmaxAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EzsignsignatureRequestTest Class Doc Comment
 *
 * @category    Class
 * @description An Ezsignsignature Object
 * @package     eZmaxAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EzsignsignatureRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EzsignsignatureRequest"
     */
    public function testEzsignsignatureRequest()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pkiEzsignsignatureID"
     */
    public function testPropertypkiEzsignsignatureID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzsignfoldersignerassociationID"
     */
    public function testPropertyfkiEzsignfoldersignerassociationID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignpagePagenumber"
     */
    public function testPropertyiEzsignpagePagenumber()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignsignatureX"
     */
    public function testPropertyiEzsignsignatureX()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignsignatureY"
     */
    public function testPropertyiEzsignsignatureY()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignsignatureWidth"
     */
    public function testPropertyiEzsignsignatureWidth()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignsignatureHeight"
     */
    public function testPropertyiEzsignsignatureHeight()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignsignatureStep"
     */
    public function testPropertyiEzsignsignatureStep()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignsignatureType"
     */
    public function testPropertyeEzsignsignatureType()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzsigndocumentID"
     */
    public function testPropertyfkiEzsigndocumentID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "tEzsignsignatureTooltip"
     */
    public function testPropertytEzsignsignatureTooltip()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignsignatureTooltipposition"
     */
    public function testPropertyeEzsignsignatureTooltipposition()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignsignatureFont"
     */
    public function testPropertyeEzsignsignatureFont()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzsignfoldersignerassociationIDValidation"
     */
    public function testPropertyfkiEzsignfoldersignerassociationIDValidation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bEzsignsignatureHandwritten"
     */
    public function testPropertybEzsignsignatureHandwritten()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bEzsignsignatureReason"
     */
    public function testPropertybEzsignsignatureReason()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bEzsignsignatureRequired"
     */
    public function testPropertybEzsignsignatureRequired()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignsignatureAttachmentnamesource"
     */
    public function testPropertyeEzsignsignatureAttachmentnamesource()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignsignatureAttachmentdescription"
     */
    public function testPropertysEzsignsignatureAttachmentdescription()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignsignatureConsultationtrigger"
     */
    public function testPropertyeEzsignsignatureConsultationtrigger()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignsignatureValidationstep"
     */
    public function testPropertyiEzsignsignatureValidationstep()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "iEzsignsignatureMaxlength"
     */
    public function testPropertyiEzsignsignatureMaxlength()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignsignatureDefaultvalue"
     */
    public function testPropertysEzsignsignatureDefaultvalue()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignsignatureTextvalidation"
     */
    public function testPropertyeEzsignsignatureTextvalidation()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignsignatureTextvalidationcustommessage"
     */
    public function testPropertysEzsignsignatureTextvalidationcustommessage()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignsignatureRegexp"
     */
    public function testPropertysEzsignsignatureRegexp()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eEzsignsignatureDependencyrequirement"
     */
    public function testPropertyeEzsignsignatureDependencyrequirement()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
