<?php
/**
 * EzsignsignatureattachmentResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.2.1
 * Contact: support-api@ezmax.ca
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eZmaxAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * EzsignsignatureattachmentResponseTest Class Doc Comment
 *
 * @category    Class
 * @description An Ezsignsignatureattachment Object
 * @package     eZmaxAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class EzsignsignatureattachmentResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "EzsignsignatureattachmentResponse"
     */
    public function testEzsignsignatureattachmentResponse()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pkiEzsignsignatureattachmentID"
     */
    public function testPropertypkiEzsignsignatureattachmentID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEzsignsignatureID"
     */
    public function testPropertyfkiEzsignsignatureID()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "binEzsignsignatureattachmentMD5"
     */
    public function testPropertybinEzsignsignatureattachmentMD5()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sEzsignsignatureattachmentName"
     */
    public function testPropertysEzsignsignatureattachmentName()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sDownloadUrl"
     */
    public function testPropertysDownloadUrl()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
