<?php
/**
 * UserResponseTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  eZmaxAPI
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * eZmax API Definition (Full)
 *
 * This API expose all the functionnalities for the eZmax and eZsign applications.
 *
 * The version of the OpenAPI document: 1.1.18
 * Contact: support-api@ezmax.ca
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.6.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace eZmaxAPI\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * UserResponseTest Class Doc Comment
 *
 * @category    Class
 * @description A User Object
 * @package     eZmaxAPI
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class UserResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "UserResponse"
     */
    public function testUserResponse()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "pkiUserID"
     */
    public function testPropertyPkiUserID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiAgentID"
     */
    public function testPropertyFkiAgentID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiBrokerID"
     */
    public function testPropertyFkiBrokerID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiAssistantID"
     */
    public function testPropertyFkiAssistantID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiEmployeeID"
     */
    public function testPropertyFkiEmployeeID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiCompanyIDDefault"
     */
    public function testPropertyFkiCompanyIDDefault()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sCompanyNameX"
     */
    public function testPropertySCompanyNameX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiDepartmentIDDefault"
     */
    public function testPropertyFkiDepartmentIDDefault()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sDepartmentNameX"
     */
    public function testPropertySDepartmentNameX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiTimezoneID"
     */
    public function testPropertyFkiTimezoneID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sTimezoneName"
     */
    public function testPropertySTimezoneName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiLanguageID"
     */
    public function testPropertyFkiLanguageID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sLanguageNameX"
     */
    public function testPropertySLanguageNameX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objEmail"
     */
    public function testPropertyObjEmail()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiBillingentityinternalID"
     */
    public function testPropertyFkiBillingentityinternalID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sBillingentityinternalDescriptionX"
     */
    public function testPropertySBillingentityinternalDescriptionX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objPhoneHome"
     */
    public function testPropertyObjPhoneHome()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objPhoneSMS"
     */
    public function testPropertyObjPhoneSMS()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiSecretquestionID"
     */
    public function testPropertyFkiSecretquestionID()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "fkiModuleIDForm"
     */
    public function testPropertyFkiModuleIDForm()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sModuleNameX"
     */
    public function testPropertySModuleNameX()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eUserOrigin"
     */
    public function testPropertyEUserOrigin()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eUserType"
     */
    public function testPropertyEUserType()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eUserLogintype"
     */
    public function testPropertyEUserLogintype()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sUserFirstname"
     */
    public function testPropertySUserFirstname()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sUserLastname"
     */
    public function testPropertySUserLastname()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sUserLoginname"
     */
    public function testPropertySUserLoginname()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "eUserEzsignaccess"
     */
    public function testPropertyEUserEzsignaccess()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dtUserLastlogondate"
     */
    public function testPropertyDtUserLastlogondate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dtUserPasswordchanged"
     */
    public function testPropertyDtUserPasswordchanged()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "dtUserEzsignprepaidexpiration"
     */
    public function testPropertyDtUserEzsignprepaidexpiration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bUserIsactive"
     */
    public function testPropertyBUserIsactive()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bUserValidatebyadministration"
     */
    public function testPropertyBUserValidatebyadministration()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bUserValidatebydirector"
     */
    public function testPropertyBUserValidatebydirector()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bUserAttachmentautoverified"
     */
    public function testPropertyBUserAttachmentautoverified()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "bUserChangepassword"
     */
    public function testPropertyBUserChangepassword()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "objAudit"
     */
    public function testPropertyObjAudit()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
